### ISSUE TITLE
About the .pkl file

### ISSUE THREAD

**Issue by qzhang852** [Daniel-xsy/RoboBEV#5]
Thank you for your excellent work. When trying to generate the nuscnes-C dataset, I met an error that 
```
Traceback (most recent call last):
  File "tools/generate_dataset.py", line 127, in <module>
    main()
  File "tools/generate_dataset.py", line 97, in main
    test = dataset[0]
  File "/workspace/RoboBEV/corruptions/project/mmdet3d_plugin/datasets/custom_nuscenes_dataset.py", line 176, in __getitem__
    return self.prepare_test_data(idx)
  File "/workspace/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 245, in prepare_test_data
    input_dict = self.get_data_info(index)
  File "/workspace/RoboBEV/corruptions/project/mmdet3d_plugin/datasets/custom_nuscenes_dataset.py", line 114, in get_data_info
    prev_idx=info['prev'],
KeyError: 'prev'
``` 
The dataset is nuscenes-mini and I generated the pkl from mmdet3d rep. I wonder which version of pkl do you use? The same as in  Cylinder3D or others like BEVFormer.  Really appreciate your help。

**Comment by Daniel-xsy** [comment]
Hi, I use the `.pkl` file in BEVFormer. You can generate it by following the instruction in the repo of BEVFormer.
